# Generated by Django 6.0.5 on 2026-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
