# Generated by Django 6.0.5 on 2026-05-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('walk', 'Walk'), ('rest', 'Rest'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('duration_mins', models.IntegerField(default=0)),
                ('intensity', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.CharField(blank=True, max_length=50)),
                ('duration_secs', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('youtube_query', models.CharField(blank=True, max_length=300)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.exerciseday')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exerciseday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='exercise.exerciseplan'),
        ),
    ]
