# Generated by Django 6.0.5 on 2026-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
